insert into Categories (id, name, description) values (1, 'Cras in purus eu magna vulputate luctus.', 'Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem. Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy.');
insert into Categories (id, name, description) values (2, 'Morbi vel lectus in quam fringilla rhoncus.', 'Quisque porta volutpat erat.');
insert into Categories (id, name, description) values (3, 'Nullam sit amet turpis elementum ligula vehicula consequat.', 'Ut at dolor quis odio consequat varius. Integer ac leo.');
insert into Categories (id, name, description) values (4, 'Proin at turpis a pede posuere nonummy. Integer non velit.', 'Nulla ac enim.');
insert into Categories (id, name, description) values (5, 'Nunc nisl.', 'Fusce consequat. Nulla nisl. Nunc nisl.');
insert into Categories (id, name, description) values (6, 'Donec dapibus. Duis at velit eu est congue elementum.', 'Suspendisse potenti. Cras in purus eu magna vulputate luctus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien.');
insert into Categories (id, name, description) values (7, 'Vestibulum sed magna at nunc commodo placerat.', 'Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem. Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat.');
insert into Categories (id, name, description) values (8, 'Maecenas ut massa quis augue luctus tincidunt.', 'Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.');
insert into Categories (id, name, description) values (9, 'Mauris lacinia sapien quis libero. Nullam sit amet turpis elementum ligula vehicula consequat.', 'Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue.');
insert into Categories (id, name, description) values (10, 'Quisque ut erat. Curabitur gravida nisi at nibh.', 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam.');
insert into Categories (id, name, description) values (11, 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam.', 'Donec semper sapien a libero.');
insert into Categories (id, name, description) values (12, 'Proin interdum mauris non ligula pellentesque ultrices.', 'Pellentesque ultrices mattis odio.');
insert into Categories (id, name, description) values (13, 'Nunc rhoncus dui vel sem.', 'Maecenas pulvinar lobortis est.');
insert into Categories (id, name, description) values (14, 'In congue. Etiam justo.', 'Proin leo odio, porttitor id, consequat in, consequat ut, nulla.');
insert into Categories (id, name, description) values (15, 'Sed ante.', 'Integer non velit.');
insert into Categories (id, name, description) values (16, 'In est risus, auctor sed, tristique in, tempus sit amet, sem.', 'Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.');
insert into Categories (id, name, description) values (17, 'Morbi ut odio. Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo.', 'Cras in purus eu magna vulputate luctus.');
insert into Categories (id, name, description) values (18, 'Sed accumsan felis.', 'Vivamus in felis eu sapien cursus vestibulum.');
insert into Categories (id, name, description) values (19, 'Proin at turpis a pede posuere nonummy.', 'Proin interdum mauris non ligula pellentesque ultrices.');
insert into Categories (id, name, description) values (20, 'Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh. Quisque id justo sit amet sapien dignissim vestibulum.', 'In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus. Nulla ut erat id mauris vulputate elementum.');
insert into Categories (id, name, description) values (21, 'Pellentesque viverra pede ac diam.', 'Cras in purus eu magna vulputate luctus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.');
insert into Categories (id, name, description) values (22, 'Suspendisse accumsan tortor quis turpis.', 'Phasellus sit amet erat.');
insert into Categories (id, name, description) values (23, 'Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.', 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi.');
insert into Categories (id, name, description) values (24, 'Mauris lacinia sapien quis libero.', 'Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl.');
insert into Categories (id, name, description) values (25, 'Donec vitae nisi. Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla.', 'Cras pellentesque volutpat dui.');
insert into Categories (id, name, description) values (26, 'Nulla nisl.', 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien.');
insert into Categories (id, name, description) values (27, 'Donec ut mauris eget massa tempor convallis.', 'Duis at velit eu est congue elementum.');
insert into Categories (id, name, description) values (28, 'Suspendisse potenti.', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit.');
insert into Categories (id, name, description) values (29, 'Morbi a ipsum.', 'Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.');
insert into Categories (id, name, description) values (30, 'Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus.', 'Nulla mollis molestie lorem. Quisque ut erat.');
insert into Categories (id, name, description) values (31, 'In congue.', 'Sed ante. Vivamus tortor. Duis mattis egestas metus. Aenean fermentum.');
insert into Categories (id, name, description) values (32, 'Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.', 'Vestibulum sed magna at nunc commodo placerat. Praesent blandit.');
insert into Categories (id, name, description) values (33, 'Nullam varius.', 'Cras in purus eu magna vulputate luctus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien.');
insert into Categories (id, name, description) values (34, 'Praesent lectus.', 'Donec posuere metus vitae ipsum. Aliquam non mauris. Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet.');
insert into Categories (id, name, description) values (35, 'Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci.', 'Curabitur convallis. Duis consequat dui nec nisi volutpat eleifend.');
insert into Categories (id, name, description) values (36, 'Nulla mollis molestie lorem.', 'Integer tincidunt ante vel ipsum.');
insert into Categories (id, name, description) values (37, 'Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est.', 'Mauris ullamcorper purus sit amet nulla.');
insert into Categories (id, name, description) values (38, 'Pellentesque eget nunc.', 'Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.');
insert into Categories (id, name, description) values (39, 'Duis ac nibh.', 'Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis. Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl.');
insert into Categories (id, name, description) values (41, 'Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.', 'Morbi non quam nec dui luctus rutrum. Nulla tellus.');
insert into Categories (id, name, description) values (42, 'Aliquam non mauris.', 'Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis.');
insert into Categories (id, name, description) values (43, 'Vivamus vel nulla eget eros elementum pellentesque.', 'Mauris ullamcorper purus sit amet nulla.');
insert into Categories (id, name, description) values (44, 'Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.', 'Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.');
insert into Categories (id, name, description) values (45, 'In est risus, auctor sed, tristique in, tempus sit amet, sem. Fusce consequat.', 'In hac habitasse platea dictumst.');
insert into Categories (id, name, description) values (46, 'Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum.', 'Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo. Aliquam quis turpis eget elit sodales scelerisque.');
insert into Categories (id, name, description) values (47, 'Duis mattis egestas metus. Aenean fermentum.', 'In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo. Aliquam quis turpis eget elit sodales scelerisque.');
insert into Categories (id, name, description) values (48, 'Praesent blandit. Nam nulla.', 'Nunc rhoncus dui vel sem. Sed sagittis.');
insert into Categories (id, name, description) values (49, 'Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim.', 'Suspendisse potenti. Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.');
insert into Categories (id, name, description) values (50, 'Cras non velit nec nisi vulputate nonummy.', 'Mauris lacinia sapien quis libero.');
insert into Categories (id, name, description) values (51, 'Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros.', 'Praesent id massa id nisl venenatis lacinia.');
insert into Categories (id, name, description) values (52, 'Morbi non quam nec dui luctus rutrum. Nulla tellus.', 'Quisque porta volutpat erat.');
insert into Categories (id, name, description) values (53, 'Nulla ut erat id mauris vulputate elementum.', 'Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl. Aenean lectus.');
insert into Categories (id, name, description) values (54, 'Praesent blandit lacinia erat.', 'Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros.');

insert into States (id, description, name) values (1, 'Vivamus in felis eu sapien cursus vestibulum. Proin eu mi.', 'Red');
insert into States (id, description, name) values (2, 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.', 'Orange');
insert into States (id, description, name) values (3, 'Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.', 'Aquamarine');
insert into States (id, description, name) values (4, 'Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros. Vestibulum ac est lacinia nisi venenatis tristique.', 'Yellow');
insert into States (id, description, name) values (30, 'Suspendisse potenti. Cras in purus eu magna vulputate luctus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', 'Mauv');
insert into States (id, description, name) values (31, 'Etiam faucibus cursus urna. Ut tellus.', 'Blue');
insert into States (id, description, name) values (38, 'In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.', 'Teal');
insert into States (id, description, name) values (40, 'Morbi a ipsum.', 'Purple');
