insert into public."Activity" (id, "Category_id", name, description) values (1, 1, 'Dabtype', 'Epoxy Flooring');
insert into public."Activity" (id, "Category_id", name, description) values (2, 3, 'LiveZ', 'Landscaping & Irrigation');
insert into public."Activity" (id, "Category_id", name, description) values (3, 3, 'Wikizz', 'Glass & Glazing');
insert into public."Activity" (id, "Category_id", name, description) values (4, 2, 'Edgeify', 'Curb & Gutter');
insert into public."Activity" (id, "Category_id", name, description) values (5, 2, 'Talane', 'Masonry & Precast');
insert into public."Activity" (id, "Category_id", name, description) values (6, 1, 'Skibox', 'Roofing (Asphalt)');
insert into public."Activity" (id, "Category_id", name, description) values (7, 3, 'Jabberbean', 'Drywall & Acoustical (MOB)');
insert into public."Activity" (id, "Category_id", name, description) values (8, 2, 'Linkbridge', 'Fire Sprinkler System');
insert into public."Activity" (id, "Category_id", name, description) values (9, 2, 'Pixoboo', 'Framing (Steel)');
insert into public."Activity" (id, "Category_id", name, description) values (10, 3, 'Blogspan', 'Soft Flooring and Base');
insert into public."Activity" (id, "Category_id", name, description) values (11, 3, 'Kamba', 'Marlite Panels (FED)');
insert into public."Activity" (id, "Category_id", name, description) values (12, 3, 'Mycat', 'Painting & Vinyl Wall Covering');
insert into public."Activity" (id, "Category_id", name, description) values (13, 2, 'Vitz', 'Retaining Wall and Brick Pavers');
insert into public."Activity" (id, "Category_id", name, description) values (14, 2, 'Wordpedia', 'Fire Protection');
insert into public."Activity" (id, "Category_id", name, description) values (15, 1, 'Camido', 'Construction Clean and Final Clean');
insert into public."Activity" (id, "Category_id", name, description) values (16, 2, 'Quimm', 'Site Furnishings');
insert into public."Activity" (id, "Category_id", name, description) values (17, 2, 'Bubblemix', 'Masonry & Precast');
insert into public."Activity" (id, "Category_id", name, description) values (18, 2, 'Quinu', 'Rebar & Wire Mesh Install');
insert into public."Activity" (id, "Category_id", name, description) values (19, 2, 'Wordify', 'Plumbing & Medical Gas');
insert into public."Activity" (id, "Category_id", name, description) values (20, 3, 'Meevee', 'Roofing (Asphalt)');
insert into public."Activity" (id, "Category_id", name, description) values (21, 2, 'Twinte', 'Waterproofing & Caulking');
insert into public."Activity" (id, "Category_id", name, description) values (22, 1, 'Edgewire', 'Masonry & Precast');
insert into public."Activity" (id, "Category_id", name, description) values (23, 2, 'Voonyx', 'Elevator');
insert into public."Activity" (id, "Category_id", name, description) values (24, 2, 'Wikizz', 'Exterior Signage');
insert into public."Activity" (id, "Category_id", name, description) values (25, 1, 'Buzzdog', 'Termite Control');
insert into public."Activity" (id, "Category_id", name, description) values (26, 3, 'Zoozzy', 'Hard Tile & Stone');
insert into public."Activity" (id, "Category_id", name, description) values (27, 1, 'Edgeify', 'Curb & Gutter');
insert into public."Activity" (id, "Category_id", name, description) values (28, 3, 'Jetpulse', 'Retaining Wall and Brick Pavers');
insert into public."Activity" (id, "Category_id", name, description) values (29, 3, 'Ailane', 'Framing (Wood)');
insert into public."Activity" (id, "Category_id", name, description) values (30, 2, 'Rhynyx', 'Epoxy Flooring');
insert into public."Activity" (id, "Category_id", name, description) values (31, 2, 'Skajo', 'Rebar & Wire Mesh Install');
insert into public."Activity" (id, "Category_id", name, description) values (32, 1, 'Dabshots', 'Structural and Misc Steel (Fabrication)');
insert into public."Activity" (id, "Category_id", name, description) values (33, 2, 'Jaxspan', 'Structural & Misc Steel Erection');
insert into public."Activity" (id, "Category_id", name, description) values (34, 2, 'Minyx', 'Casework');
insert into public."Activity" (id, "Category_id", name, description) values (35, 2, 'Rhycero', 'Drywall & Acoustical (MOB)');
insert into public."Activity" (id, "Category_id", name, description) values (36, 2, 'Meeveo', 'Temp Fencing, Decorative Fencing and Gates');
insert into public."Activity" (id, "Category_id", name, description) values (37, 3, 'Livetube', 'Fire Protection');
insert into public."Activity" (id, "Category_id", name, description) values (38, 3, 'Layo', 'Plumbing & Medical Gas');
insert into public."Activity" (id, "Category_id", name, description) values (39, 2, 'Bluejam', 'Doors, Frames & Hardware');
insert into public."Activity" (id, "Category_id", name, description) values (40, 1, 'Rhyzio', 'Elevator');
insert into public."Activity" (id, "Category_id", name, description) values (41, 2, 'Realcube', 'Overhead Doors');
insert into public."Activity" (id, "Category_id", name, description) values (42, 1, 'Demivee', 'Masonry & Precast');
insert into public."Activity" (id, "Category_id", name, description) values (43, 1, 'Jaxbean', 'Structural and Misc Steel (Fabrication)');
insert into public."Activity" (id, "Category_id", name, description) values (44, 2, 'Brainsphere', 'Asphalt Paving');
insert into public."Activity" (id, "Category_id", name, description) values (45, 2, 'Mudo', 'RF Shielding');
insert into public."Activity" (id, "Category_id", name, description) values (46, 3, 'Kimia', 'Wall Protection');
insert into public."Activity" (id, "Category_id", name, description) values (47, 2, 'Vinte', 'Casework');
insert into public."Activity" (id, "Category_id", name, description) values (48, 3, 'Twitterwire', 'Sitework & Site Utilities');
insert into public."Activity" (id, "Category_id", name, description) values (49, 2, 'Dynazzy', 'Drywall & Acoustical (FED)');
insert into public."Activity" (id, "Category_id", name, description) values (50, 1, 'Eadel', 'Epoxy Flooring');
insert into public."Activity" (id, "Category_id", name, description) values (51, 2, 'Quinu', 'Sitework & Site Utilities');
insert into public."Activity" (id, "Category_id", name, description) values (52, 2, 'Aimbo', 'Rebar & Wire Mesh Install');
insert into public."Activity" (id, "Category_id", name, description) values (53, 3, 'Skilith', 'Structural & Misc Steel Erection');
insert into public."Activity" (id, "Category_id", name, description) values (54, 2, 'Avamba', 'Casework');
insert into public."Activity" (id, "Category_id", name, description) values (55, 1, 'Quatz', 'Fire Sprinkler System');
insert into public."Activity" (id, "Category_id", name, description) values (56, 1, 'Lazzy', 'Ornamental Railings');
insert into public."Activity" (id, "Category_id", name, description) values (57, 1, 'Avavee', 'Waterproofing & Caulking');
insert into public."Activity" (id, "Category_id", name, description) values (58, 1, 'Thoughtblab', 'Curb & Gutter');
insert into public."Activity" (id, "Category_id", name, description) values (59, 2, 'Gigabox', 'Casework');
insert into public."Activity" (id, "Category_id", name, description) values (60, 3, 'Avaveo', 'HVAC');
insert into public."Activity" (id, "Category_id", name, description) values (61, 3, 'Dabjam', 'Masonry');
insert into public."Activity" (id, "Category_id", name, description) values (62, 2, 'Einti', 'EIFS');
insert into public."Activity" (id, "Category_id", name, description) values (63, 3, 'Eabox', 'Termite Control');
insert into public."Activity" (id, "Category_id", name, description) values (64, 2, 'Mynte', 'Drilled Shafts');
insert into public."Activity" (id, "Category_id", name, description) values (65, 2, 'Oozz', 'Framing (Wood)');
insert into public."Activity" (id, "Category_id", name, description) values (66, 1, 'BlogXS', 'Waterproofing & Caulking');
insert into public."Activity" (id, "Category_id", name, description) values (67, 3, 'Skinder', 'Landscaping & Irrigation');
insert into public."Activity" (id, "Category_id", name, description) values (68, 1, 'Tazz', 'Elevator');
insert into public."Activity" (id, "Category_id", name, description) values (69, 1, 'Plajo', 'Painting & Vinyl Wall Covering');
insert into public."Activity" (id, "Category_id", name, description) values (70, 1, 'Flashdog', 'Plumbing & Medical Gas');
insert into public."Activity" (id, "Category_id", name, description) values (71, 2, 'Mymm', 'Framing (Wood)');
insert into public."Activity" (id, "Category_id", name, description) values (72, 1, 'Twitterbeat', 'Drilled Shafts');
insert into public."Activity" (id, "Category_id", name, description) values (73, 3, 'Topicblab', 'Glass & Glazing');
insert into public."Activity" (id, "Category_id", name, description) values (74, 3, 'Meezzy', 'Masonry');
insert into public."Activity" (id, "Category_id", name, description) values (75, 1, 'Digitube', 'Casework');
insert into public."Activity" (id, "Category_id", name, description) values (76, 1, 'Buzzster', 'Landscaping & Irrigation');
insert into public."Activity" (id, "Category_id", name, description) values (77, 2, 'Tanoodle', 'Overhead Doors');
insert into public."Activity" (id, "Category_id", name, description) values (78, 2, 'Mycat', 'Rebar & Wire Mesh Install');
insert into public."Activity" (id, "Category_id", name, description) values (79, 2, 'Divanoodle', 'Framing (Wood)');
insert into public."Activity" (id, "Category_id", name, description) values (80, 1, 'Jabbersphere', 'Roofing (Asphalt)');
insert into public."Activity" (id, "Category_id", name, description) values (81, 1, 'Wordtune', 'Doors, Frames & Hardware');
insert into public."Activity" (id, "Category_id", name, description) values (82, 2, 'Flipstorm', 'Casework');
insert into public."Activity" (id, "Category_id", name, description) values (83, 1, 'Yodel', 'Drywall & Acoustical (FED)');
insert into public."Activity" (id, "Category_id", name, description) values (84, 3, 'Rhyloo', 'Termite Control');
insert into public."Activity" (id, "Category_id", name, description) values (85, 3, 'Blogtag', 'Soft Flooring and Base');
insert into public."Activity" (id, "Category_id", name, description) values (86, 2, 'Livepath', 'Roofing (Metal)');
insert into public."Activity" (id, "Category_id", name, description) values (87, 3, 'Voolith', 'Waterproofing & Caulking');
insert into public."Activity" (id, "Category_id", name, description) values (88, 1, 'Podcat', 'Drilled Shafts');
insert into public."Activity" (id, "Category_id", name, description) values (89, 2, 'Dablist', 'Drilled Shafts');
insert into public."Activity" (id, "Category_id", name, description) values (90, 1, 'Tagchat', 'Site Furnishings');
insert into public."Activity" (id, "Category_id", name, description) values (91, 2, 'Blogspan', 'Ornamental Railings');
insert into public."Activity" (id, "Category_id", name, description) values (92, 2, 'Kaymbo', 'EIFS');
insert into public."Activity" (id, "Category_id", name, description) values (93, 1, 'Npath', 'Fire Protection');
insert into public."Activity" (id, "Category_id", name, description) values (94, 1, 'Browseblab', 'Asphalt Paving');
insert into public."Activity" (id, "Category_id", name, description) values (95, 3, 'Divanoodle', 'Masonry & Precast');
insert into public."Activity" (id, "Category_id", name, description) values (96, 1, 'Topicstorm', 'Termite Control');
insert into public."Activity" (id, "Category_id", name, description) values (97, 3, 'Katz', 'EIFS');
insert into public."Activity" (id, "Category_id", name, description) values (98, 1, 'Voonte', 'Granite Surfaces');
insert into public."Activity" (id, "Category_id", name, description) values (99, 3, 'Twinder', 'Electrical and Fire Alarm');
insert into public."Activity" (id, "Category_id", name, description) values (100, 2, 'Topicshots', 'Structural and Misc Steel (Fabrication)');

